### ISSUE TITLE
能否提供更完整的配置样例？

### ISSUE THREAD

**Issue by zjengjie** [v3aqb/fwlite-cli#1]
如simple-obfs，kcptun如何配置？

**Comment by v3aqb** [comment]
How to work with SIP003 plugin:
====================

step 1: tell fwlite where the plugin executable is located.
----------

In the configuration file, section [plugin].

```
[plugin]
kcptun = path_to_kcptun_client
simple-obfs = path_to_simple-obfs
```

path can be relative path (to the config file),  absolute path, or name of the executable located within environment variable PATH.

For kcptun: use the [original kcptun](https://github.com/xtaci/kcptun), not the modified SIP003 version.

step 2: add parent proxy.
------------

Same as [SIP002](https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html) from shadowsocks.

```
[parents]
proxy5 = ss://cmM0LW1kNTpwYXNzd29yZA==@host:80/?plugin=simple-obfs%3Bobfs%3Dhttp%3Bobfs-host%3Dwww.baidu.com
```

Plugins can be applied to any proxy protocol that is supported, not limited to shadowsocks.

More, if the plugin is based on TCP (unlike `kcptun`, or v2ray-plugin in `quic` mode), proxy chain can be used.

```
[parents]
proxy6 = ss://cmM0LW1kNTpwYXNzd29yZA==@host:80/?plugin=simple-obfs%3Bobfs%3Dhttp%3Bobfs-host%3Dwww.baidu.com|http://proxy.server:8118
```

**Comment by zjengjie** [comment]
thanks
