### ISSUE TITLE
parent是http proxy的时候并且有用户名密码的时候有问题

### ISSUE THREAD

**Issue by lilaboc** [v3aqb/fwlite-cli#2]
connection.py里面的80行这一句
req.append('Proxy-Authorization: Basic %s\r\n' % base64.b64encode(auth.encode()))

base64.b64encode()会返回一个byte类型, 需要改成
req.append('Proxy-Authorization: Basic %s\r\n' % base64.b64encode(auth.encode()).decode())
才能正常工作

**Comment by v3aqb** [comment]
confirmed. my bad.
